server:
  port: 8222
logging:
  level:
    root: debug
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    security:
      jwt-secret: ae787f1c945826ac0643570e54a9d564e24fcc1bee7d18f56957d3d522126a359ddcd8a8
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users-api
              uri: http://localhost:8090
              predicates:
                - Path=/api/users/**
            - id: auth-api
              uri: http://localhost:8090
              predicates:
                - Path=/api/auth/**
            - id: events-api
              uri: http://localhost:8888
              predicates:
                - Path=/api/events/**
